build:
	g++ -std=c++11 *.cpp -o project2
run:
	./project2.out part1.tga layer1.tga multiply pattern1.tga
	./project2.out part2.tga layer2.tga subtract car.tga
	./project2.out part3.tga text.tga screen layer1.tga pattern2.tga
	./project2.out part4.tga layer2.tga multiply circles.tga subtract pattern2.tga
	./project2.out part5.tga layer1.tga overlay pattern1.tga
	./project2.out part6.tga car.tga addgreen 200
	./project2.out part7.tga car.tga scalered 4 scaleblue 0
	./project2.out part8_r.tga car.tga onlyred
	./project2.out part8_g.tga car.tga onlygreen
	./project2.out part8_b.tga car.tga onlyblue
	./project2.out part9.tga layer_red.tga combine layer_green.tga layer_blue.tga
	./project2.out part10.tga text2.tga flip
	